AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket
Resources:
  UdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: website-artifacts
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
PublicBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref UdaBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:PutObject
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${UdaBucket}/*'

Outputs:
  WebsiteURL:
    Value: !GetAtt UdaBucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !GetAtt UdaBucket.DomainName
    Description: Name of S3 bucket to hold website content
  
